session.go

Ran tests and found no errors
PASS
ok      _/home/rpkamp/quickfix   0.007s

Signal application when connection is gone (server disconnects)

---

acceptor.go
connection.go
initiator.go
session.go

Implemented acceptor.Stop() and initiator.Stop(), and made sure the application is always notified when the connection is dropped, i.e., when session.run() finishes.

Stop connections, properly signal app when connection dropped

---

boolean_field.go
boolean_field_test.go
field.go
field_map.go
float_field.go
float_field_test.go
int_field.go
int_field_test.go
message.go
message_test.go
repeating_group.go
repeating_group_test.go
string_field.go
string_field_test.go
tag_value.go
utc_timestamp_field.go
validation.go

next steps...
* code gen support
* bit more KISS refactoring

adds repeating group primitive

---

field_map.go
repeating_group.go
repeating_group_test.go

Makes the repeating group interface a bit easier to use

groups -> field maps

---

marshal.go
marshal_test.go
repeating_group.go
unmarshal.go
unmarshal_test.go

Experimental feature.  Uses reflection for cleaner message type abstraction.

Message Reflection

---

field_map.go
field_map_test.go
marshal.go
marshal_test.go
reflection.go
unmarshal.go

Affects behavior for marshaling messages with empty groups

added omit_empty struct tag for groups

---

Makefile
_gen/generate-components/main.go
errors.go
field_map.go
fix40/header.go
fix40/trailer.go
fix41/header.go
fix41/trailer.go
fix42/header.go
fix42/trailer.go
fix43/header.go
fix43/trailer.go
fix44/header.go
fix44/trailer.go
fix_utc_timestamp.go
fix_utc_timestamp_test.go
fixt11/header.go
fixt11/trailer.go
marshal.go
marshal_test.go
reflection.go
unmarshal.go

Includes misc test fixes, and some api changes for example app use

generate header, trailer components

---

file_log.go
file_log_test.go

fix for #72

---

session.go

Fire special event to break waiting select and send queued messages immediately. 
Not using sessionEvent channel since it may already be full with one of timer events and will need to either wait (which may cause deadlock) or discard event (which still causes delays)

Fix for #80

---

datadictionary/build.go
datadictionary/datadictionary.go
datadictionary/xml.go
datadictionary/xml_test.go

refactoring data dictionary pkg

---

_gen/generate-fields/main.go
_gen/helpers.go
datadictionary/build.go
datadictionary/build_test.go
datadictionary/component_type_test.go
datadictionary/datadictionary.go
datadictionary/datadictionary_test.go
datadictionary/field_def_test.go
datadictionary/field_type_test.go
datadictionary/group_field_def_test.go
datadictionary/message_def_test.go
datadictionary/xml_test.go
validation.go

Increased test coverage and general refactoring of datadictionary package.  Fixes similar, but not same bug as #102

Datadictionary tests

---

config/doc.go
doc.go
gen/generate-components/main.go
gen/generate-messages/main.go
marshal_test.go

appeasing the static analysis tools...

spelling, fmtness

---

session.go

fixes #127
I was able to confirm the bug proposed in issue #127 by removing the DataDictionary config option in one of the quickfix test cfg files.
The following changes include:
- Perform a `nil` check that the `validator` has been initialized
- Prevent the `validator` from being initialized if the Data Dictionary requirements have not been met.

check for initialized session validator before validating message

---

.travis.yml
Makefile

pipelines travis builds for faster elapsed time, quicker fails

faster travis build times

---

file_log.go

message file log includes timestamps, all file logs are utc

---

gen/generate-fields/main.go

refactoring enum generation

---

doc.go
message.go
registry.go

removes marshal cruft

---

cmd/generate/main.go

much faster message generation when generating all fix messages

pipelining generation

---

initiator.go

This change is comparable to #156.
It reduces unnecessary complexity and removes potential concurrent operations on a map.

Removed complexity around closing Initiator sessions

---

in_session.go
latent_state.go
logon_state.go
logout_state.go
resend_state.go
session.go
session_state.go
session_test.go

code cleanup from fallout of #182

refactoring of session code

---

session.go
session_test.go

ToApp error code was previously ignored

fixes donotsend logic

---

resend_state_test.go
session_test.go
test_helpers.go

reusable testing for session scenarios

test refactoring, leveraging testify mock assertions

---

logout_state.go
logout_state_test.go
session.go
session_test.go

session in the logout state will process messages before logout ack or timeout

---

errors.go
session.go
session_test.go

send returns donotsend error

---

config/configuration.go
config/doc.go
in_session.go
in_session_test.go
logout_state_test.go
session.go
session_test.go

implements reset on logout

---

Makefile
config/configuration.go
internal/time_range.go
internal/time_range_test.go
quickfix_test.go
session.go
session_test.go
test_helpers.go

Session time configuration

---

in_session.go
in_session_test.go
internal/time_range.go
internal/time_range_test.go
logon_state.go
logon_state_test.go
logout_state_test.go
pending_timeout_test.go
quickfix_test.go
resend_state_test.go
session.go
session_state.go
session_test.go

Refs #31 
mostly refactoring towards session scheduling. adds in same range to time range

Session time

---

session.go
session_test.go

adds ticker for session time checking

---

in_session.go
internal/time_range.go
internal/time_range_test.go
logon_state_test.go
session.go

* bug fix in recent time range/same range code around time zones
* some minor DRY refactoring

Session Time Timezone fix

---

in_session_test.go
latent_state_test.go
logon_state_test.go
logout_state_test.go
not_session_time.go
not_session_time_test.go
pending_timeout_test.go
quickfix_test.go
session_state.go
session_test.go

fixes some flakey session time behavior, better test coverage

---

quickfix_test.go
session.go
session_state.go
session_test.go
test_helpers.go

only accept, initiate during session time

---

acceptor.go
connection.go
connection_internal_test.go
in_session_test.go
initiator.go
latent_state.go
latent_state_test.go
logon_state.go
logon_state_test.go
logout_state.go
logout_state_test.go
not_session_time.go
not_session_time_test.go
quickfix_test.go
session.go
session_state.go
session_test.go

Refs #31
cleans up vestigial logic from before session time changes

clean disconnect on initiator/acceptor stop

---

internal/time_range.go
internal/time_range_test.go

fixes another same range bug

---

config/configuration.go
internal/time_range.go
internal/time_range_test.go
session.go
session_test.go

TimeZone configuration

---

config/configuration.go
config/doc.go
internal/time_range.go
internal/time_range_test.go
session.go
session_test.go

StartDay, EndDay for week long sessions

---

acceptor.go
connection.go
initiator.go
message_router_test.go
registry.go
session.go

KISS on registry, session management

---

_test/fix50.cfg
_test/fix50sp1.cfg
_test/fix50sp2.cfg
session.go
session_test.go

correctly translate default appl ver id in config

---

acceptor.go
config/configuration.go
config/doc.go
initiator.go

closes #83
allows socket connect host to be an ipv6 address

adds socket accept host, ipv6 support

---

config/doc.go
initiator.go
internal/session_settings.go
session_factory.go
session_factory_test.go

adds SocketConnectHost/Port<n>

---

internal/time_range.go
internal/time_range_test.go
session_state.go

fixes bug for 24 hour session

---

cmd/generate-fix/internal/template_helpers.go
cmd/generate-fix/internal/templates.go

only imports decimal package if there are decimal fields

---

internal/time_range.go
internal/time_range_test.go

say the startDay==endDay==Sunday, the current day is Monday. it should return `false` unless startTime >= endTime

Fix time range

---

config/configuration.go
config/doc.go
in_session.go
in_session_test.go
internal/session_settings.go
resend_state.go
resend_state_test.go
session.go
session_factory.go
session_factory_test.go

resend chunking

---

in_session.go
in_session_test.go

drop messages with too low seq num and poss dup

---

message_router.go
message_router_test.go

fixes router so it does not reject admin, biz reject messages

---

field_map.go
field_map_test.go

Another utility methods for FieldMap.

Add FieldMap.{GetBool, SetBool}

---

acceptor.go
config/configuration.go
config/doc.go
session.go
session_id.go
session_id_test.go
session_test.go
settings.go
settings_test.go

adds sender/target sub and location configuration

---

file_log.go

Fixes issue introduced in #260

fixes file log output for incoming, outgoing

---

field_map.go
message.go
message_router.go
session.go

also adds GetTime to field map

reduces allocs more

---

config/configuration.go
config/doc.go
internal/session_settings.go
session.go
session_factory.go
session_factory_test.go
session_test.go

adds check latency configuration

---

cmd/generate-fix/internal/templates.go
config/configuration.go
config/doc.go
field/fields.generated.go
fix_utc_timestamp.go
fix_utc_timestamp_test.go
session.go
session_factory.go
session_factory_test.go
session_test.go

Timestamp precision

---

config/configuration.go
config/doc.go
internal/session_settings.go
session.go
session_factory.go
session_factory_test.go
session_test.go

ResetOnDisconnect

---

config/configuration.go
config/doc.go
internal/session_settings.go
quickfix_test.go
session.go
session_factory.go
session_factory_test.go
session_test.go

max latency config

---

config/configuration.go
config/doc.go
in_session.go
in_session_test.go
internal/session_settings.go
quickfix_test.go
session.go
session_factory.go
session_factory_test.go
session_test.go

persist messages config option

---

session.go

small one liner on event logging

fixes some confusing logging on reset flag handling

---

acceptor.go
config/configuration.go

Add possibility to accept dynamic sessions by adding a flag to configuration:
```
[default]
DynamicSessions=Y
```

Dynamic sessions

---

initiator.go

I have not been able to sleep since I first saw that.

Outrageous mistake

---

session.go
session_state.go

Send error if connection is outside of session time

---

acceptor.go

Happy to move things around - however these additional sessionIds would be helpful for logging/triage purposes.

Add sessionId to global logs where possible

---

message.go
message_test.go

Cme drop copy

---

_sql/postgresql/create.bat
_sql/postgresql/create.sh
store/sql/sqlstore.go

Resolves https://github.com/quickfixgo/quickfix/issues/332 and https://github.com/quickfixgo/quickfix/issues/487

Postgres support upgrades

---

session.go

Resolves https://github.com/quickfixgo/quickfix/issues/671

Reverts ToAdmin call sequencing

---

registry.go

Resolves https://github.com/quickfixgo/quickfix/issues/380

Adds convenience getters for session log and store

---

in_session.go
in_session_test.go
logon_state.go
resend_state.go
session.go

Reverts quickfixgo/quickfix#713

Revert "Block messages when a Resend Request is active"
