settings.go
I want to be able to use lower case headers for the settings file, so as not to modify them when they are provided by a third party. This little change does the job.
=> Make settings parser case insensitive for headers

repeating_group.go, repeating_group_test.go
Check repeated group count in read and add some more tests, keeping the feature that an unknown field in the message stops the group. This is exclusive with another pull request where templates may be specified partially.
=> Better error handling when reading repeating groups

field.go, field_map.go, fix_boolean.go, fix_boolean_test.go, fix_float.go, fix_float_test.go, fix_int.go, fix_int_test.go, fix_string.go, fix_string_test.go, fix_utc_timestamp.go, message.go, parser.go, parser_test.go, repeating_group.go, repeating_group_test.go, validation.go
* Reverted some interface complexities introduced with first cut of repeating groups.  Not necessary to build repeating group templates with actual fields.
* Set message bytes capacity in parser.  Was an oversight.
=> message cap, removed repeating group cruft

field_map.go, message.go, registry.go, repeating_group.go, repeating_group_test.go, tag_value.go, tag_value_test.go, validation.go, validation_test.go
Namely making TagValue package private.  No longer necessary to expose in api.
=> hiding where appropriate, more usable send method

Makefile, acceptor.go, connection.go, connection_internal_test.go, initiator.go, session.go
closes #58 #59
some code refactoring, adds cover
=> fixes for #58 #59

in_session.go, latent_state.go, logon_state.go, logout_state.go, message_router.go, pending_timeout.go, registry.go, resend_state.go, session.go, session_state.go, session_test.go
Session does not need to be exposed to API clients
=> remove session from public api

marshal.go, marshal_test.go
walkFunc for embedded structs; correct parsing of tags like `fix:"555,omitempty"` in slices; tests updated
=> Fix for #85

_sql/mssql/create.bat, _sql/mssql/quickfix_database.sql, _sql/mysql/create.bat, _sql/mysql/create.sh, _sql/mysql/event_log_table.sql, _sql/mysql/messages_log_table.sql, _sql/mysql/messages_table.sql, _sql/mysql/mysql.sql, _sql/mysql/quickfix_database.sql, _sql/mysql/sessions_table.sql, _sql/oracle/messages_table.sql, _sql/oracle/sessions_table.sql, _sql/postgresql/create.bat, _sql/postgresql/create.sh, _sql/postgresql/event_log_table.sql, _sql/postgresql/messages_log_table.sql, _sql/postgresql/messages_table.sql, _sql/postgresql/postgresql.sql, _sql/postgresql/sessions_table.sql, _sql/sqlite3/event_log_table.sql, _sql/sqlite3/messages_log_table.sql, _sql/sqlite3/messages_table.sql, _sql/sqlite3/sessions_table.sql, config/configuration.go, config/doc.go, sqlstore.go, sqlstore_test.go, store_test.go
- New session settings: `SQLDriver` and `SQLDataSourceName`
- Uses the `sql` pkg directly (no external deps)
- The DDL files in `_sql/` are borrowed from `quickfix/c++` and `quickfix/j`
- Only tested with `sqlite3` driver so far
- Should work with the `mysql` driver (will probably need `parseTime=true` in the DSN)
- It may be useful going forward to have separate mysql, sqlite, postgresql, etc. impls of `sqlStore` to work around the differences (e.g. `DATETIME` parsing and `?` vs `$1` in prepared statements)
Refs #88
=> Add sql database impl of MessageStore

marshal.go, marshal_test.go
Original issue had to do with the handling of optional components in repeating groups.  Added test that previously panicked as #91 indicated.
=> fix for #91

filestore.go, filestore_test.go, sqlstore.go, sqlstore_test.go
`fileStore` and `sqlStore` previously accepted `SessionSettings` as config args - accepting `Settings` is more appropriate
=> Accept `Settings` instead of `SessionSettings`

settings.go, settings_test.go
Adjusted the regexp to allow equals signs in values.
Allows parsing of settings like: `SQLDataSourceName=/quickfix?parseTime=true&loc=UTC`.
=> Allow settings values to contain equals signs

marshal.go, reflection.go, unmarshal.go, unmarshal_test.go
Addresses #99.  Related to #91 fix.
=> fixes bug in unmarshalling group components

connection.go, errors.go, field_map.go, in_session.go, message.go, message_test.go, repeating_group.go, repeating_group_test.go, session.go, session_test.go, unmarshal_test.go, validation_test.go
Now returns "Repeating group fields out of order" (rej reason 15) when delim field not found.
Needed `ParseMessage` for the unit test, so addresses #110 and #77 as well.
Fixes #103 
Fixes #110
Fixes #77
=> Return better error when group delim not found

validation.go, validation_test.go
fixes #102
While "walking" over every field during message validation, each field is passed to `validateVisitField` to check and validate repeating groups if the current field happens to be the start of a repeating group. After checking the current field, it *pops that field off the stack* of remaining fields in the message.
When validating a repeating group, the starting field is passed to `validateVisitGroupField` which iterates over the remaining fields in the message, *popping each field off the stack* as it goes along.
Therefore, when the repeating group validation returns, `validateVisitField` will pop *the current* field off the stack of remaining fields, which is actually *the next* field in the message after the repeating group.
In the case of the `MarketDataRequest` message …
=> Repeating group validation

gen/generate-fields/main.go, gen/helpers.go
- Do not hardcode the root import path.
- Generated code files should have import statements that import the other locally generated code, not `"github.com/quickfixgo/quickfix"`.
- Add missing types (e.g. `UTCDATE`) to generators, which were causing `FIX42.xml` field generation to fail if run by itself.
Note: For now, users will have to copy `enum/begin_string.go` to their local `enum` directory.  Correct solution there TBD...
=> Make gen import path relative

session.go, session_id.go, validation.go, validation_test.go
Related to #107
The changes here propose a small refactor for message validation. I've created a `validator` interface, with two implementations, one for FIX, and another for FIXT. We currently have some logic in the `session` struct surrounding validation that determines which data dictionaries to use. With these changes, I've been able to move all of that decision making into the `validation` file.
Additionally, this refactor will encourage a more scalable approach for upcoming validation configuration enhancements, ex. #107
Thoughts 💭  and concerns 😰  are more than welcome. Please and thank you! 😊
=> validator interface

errors.go, field_map.go, in_session.go, message_router.go, session.go, validation.go
=> makes some reject helpers public

datadictionary/datadictionary.go, datadictionary/message_def_test.go, validation.go
Fixes a validation bug where a message is rejected when it includes a required group of size 0.  The validation will reject the message with a required tag missing if the group is defined to have required fields within it.  If the group is of size 0, those required field groups should not be included in the message.
=> fixes required group validation error

session.go
RefTagID does not appear on BusinessMessageReject type, and should not have it set.
I don't see coverage of `in_session.go` which uses `doReject`. Open approaches on that.
=> RefTagID is not known to BusinessMessageReject type

errors.go, errors_test.go
Changes proposed in this PR:
* more verbose error text on conditionally required field BusinessMessageReject
* unit test coverage of errors.go
=> More verbose error text on conditionally required field BMR 

gen/generate-components/main.go, gen/generate-fields/main.go, gen/generate-messages/main.go, gen/generate.go
generate commands will return non-zero exit code on parse errors, but will write the file(s) out for inspection.
=> better error handling in gen package

field.go, field_map.go, marshal.go, marshal_test.go, message.go, repeating_group.go, repeating_group_test.go, tag_value.go, tag_value_test.go, unmarshal.go, unmarshal_test.go, validation.go, validation_test.go
Will be necessary for generation of typed repeating groups
=> extracts repeating group interface

field/fields.go, gen/generate-fields/main.go
* Generates New and New NoMillis for UTCTimestamp fields
* New returns value instead of pointer as this is the most common use case.
Broken into two commits, f6bbe2f is gen code changes, the other generated
=> Gen value timestamp

field/fields.go, gen/generate-fields/main.go
In practice, this seems to be the more code friendly impl:
```go
//NewAccount returns a new AccountField initialized with val
func NewAccount(val string) AccountField {
return AccountField{quickfix.FIXString(val)}
}
```
vs.
```go
//NewAccount returns a new AccountField initialized with val
func NewAccount(val quickfix.FIXString) AccountField {
return AccountField{val}
}
```
The latter forces some type gymnastics in most common cases where we have a string var to pass into NewAccount.
=> Slight gen revert

config/configuration.go, config/doc.go, session_settings.go, sqlstore.go, sqlstore_test.go
When using a database server that closes inactive connections after some
duration, set `SQLConnMaxLifetime` to a value less than that duration.
Otherwise, the connection will be reused forever, and this could result in a
dropped connection.
For example, if you are using MySQL configured with `wait_timeout = 28800`, use
something like `SQLConnMaxLifetime=14400s`.
Refs #139
=> Expose sql.DB's SetConnMaxLifetime() in settings

field/fields.go, fix_boolean.go, fix_boolean_test.go, fix_float.go, fix_float_test.go, fix_int.go, fix_int_test.go, fix_string.go, fix_utc_timestamp.go, fix_utc_timestamp_test.go, gen/generate-fields/main.go, in_session.go, marshal.go, session.go, session_test.go, unmarshal.go, unmarshal_test.go, validation_test.go
* Removes some archaic field constructors
eg,
```go
f := quickfix.NewFIXString("hello")
```
`NewFIXString` and the other field constructors returned a pointer to the initialized field.  In practice, this isn't normally necessary.  A reference to a FIX field is only necessary when reading a field into a zero-valued field.  
* Adds helper convertors to field types
```go
var cs field.CollStatus
msg.Body.Get(&cs)
//Instead of...
val := int(cs.FIXInt)
//do
val = cs.Int()
```
* Embeds time.Time in FIXUTCTimestamp.  This was previously an unembedded field `Value`.  Embedding has the benefit of calling time.Time methods directly on UTCTimestamp fields.  Note that this change required regenerated fields, c0d827e
=> Misc field type refactoring

session.go
Otherwise the response to the resend request will not have the expected seq num.
=> Do not incr target seq num when seq num too high

acceptor.go, connection.go
I came across this output while debugging race conditions in my own project using the `-race` flag:
```
==================
WARNING: DATA RACE
Read by main goroutine:
runtime.mapiterinit()
/usr/local/go/src/runtime/hashmap.go:607 +0x0
[my_project]/vendor/github.com/quickfixgo/quickfix.(*Acceptor).Stop()
[my_project]/vendor/github.com/quickfixgo/quickfix/acceptor.go:58 +0x9d
main.main()
[my_project]/main.go:248 +0xf81
Previous write by goroutine 17:
runtime.mapdelete()
/usr/local/go/src/runtime/hashmap.go:545 +0x0
[my_project]/vendor/github.com/quickfixgo/quickfix.(*Acceptor).Start.func1()
[my_project]/vendor/github.com/quickfixgo/quickfix/acceptor.go:45 +0x348
Goroutine 17 (running) created at:
[my_project]/vendor/github.com/quickfixgo/quickfix.(*Acceptor).Start() …
```
=> Concurrent map operations on Acceptor.Stop()

initiator.go, session.go
Because `HeartBtInt` is a required field on logons, I added a check in the initiator to enforce it as a required configuration option. Without this, my initiator was sending logons with a `HeartBtInt` of `0`, which caused some unexpected behavior in the acceptor.
Additionally, I copied an assertion from QuickFIX/C++, ensuring that `HeartBtInt` is greater than zero.
=> Checks around HeartBtInt configuration

in_session.go, logout_state.go, session.go
Changes proposed in this pull request:
- Updates acceptor/initiator stop sequence. Sends a Logout and waits for a response before invoking the application `OnLogout` callback, per FIX standard
- Removes redundant calls to the application `OnLogout` callback. Currently, the `run()` function in `session` ultimately invokes `OnLogout` when it returns, while the `inSession` state has a few cases where it invokes the callback as well.
- Improves the event log output for the logon and logout sequences. Following the QuickFIX/C++ implementation, a proper session event sequence will look like the following:
```
2016/06/30 15:31:45.167656 Sending logon request
2016/06/30 15:31:45.185684 Received logon response
2016/06/30 15:31:49.810696 Inititated logout request
2016/06/30 15:31:49.825808 Received …
```
=> Proper FIX logout sequence

config/configuration.go, config/doc.go, connection.go, initiator.go
- Adds `ReconnectInterval` to config options
- Updates Initiator to read/validate setting, and passes it to the connection
=> Configurable reconnect interval

registry.go, session.go
Two small changes on things that were overlooked on #164
- Bubble up errors returned from message store on send
- Check if session event loop has stopped to avoid sending on a closed channel
=> Session event loop follow up

session.go
Another follow up to #164 
Calls to SendToTarget within the OnLogon callback will currently deadlock. This fix will kick that callback on a dedicated goroutine.
I did the same for OnLogout. Although that wont cause a deadlock on SendToTarget, there could be unknown side effects if an application fails to return from OnLogout, ultimately preventing the session from terminating
=> Handle OnLogon/Logout callbacks in user space

event_timer.go, session.go
We were seeing a test request (35=1) being sent immediately after logon for our acceptor. After looking into this, it appears that the `peerTimer` was being reset before having processed the logon request form the initiator. Because the initiator's logon contains the heartbeat interval, the acceptor was trying to reset the timer with a zero value, ultimately causing the peer timer to activate immediately.
The following changes will prevent timers from being reset with a zero value, and ensures that the timer is reset once the logon (and heartbeat interval) is received.
=> Reset peer timer after logon

in_session.go, session.go
fixes #170
related to #171
The logout sequence has stopped working due to the logout initiation being coupled to the `inSession` state. As identified in #171, we were seeing the session immediately sending a test request after logon. By doing so, the session state transitioned from `inSession` to `pendingTimeout`. While the `pendingTimeout` state embeds the `inSession` state, the call to `application.Stop` only checks if the current state is the `inSession` state to initiate the logout sequence.
These changes move `initiateLogout` into the session, so the action on `Stop` can check `IsLoggedOn`, and initiate the logout sequence as necessary. Therefore all states that confirm true for the `IsLoggedOn` function interface, will result in a proper logout sequence.
=> Initiate logout for all logged on states

session.go
In the case that `checkTargetTooHigh` returns true, we're exiting the logon handling before calling `OnLogon`. Even though a logon immediately starts in the resend state, we should still callback to the application that the logon completed.
=> Ensure OnLogon is called even if seq num too high

in_session.go, logout_state.go
We're currently not incrementing the next expected target sequence number when a counter party logs off. So when the session is re-established, there is a sequence number mismatch, resulting in resend requests.
=> increment target seq num on logout

in_session.go, initiator.go, session.go
=> Error handling around session code

in_session.go
Old Code was using the *target* expected sequence number instead of the *sender* expected sequence number to determine resend range.  This resulted in some very peculiar resend states as suggested by #169
=> fixes bogus resend logic

in_session.go
fixes #169
The cause of the referenced issue was due to the target seq num being incremented while *both* sides were sending the resend request. Therefore when they received the corresponding sequence reset, the sequence of that message was lower than what was erroneously expected. Looking at the quickfix/c++ code, there is in fact a check to prevent this from happening:
https://github.com/quickfix/quickfix/blob/6bc717f88f8e8c3729415a0ec65ec2615d501728/src/C%2B%2B/Session.cpp#L448-L449
=> Conditionally increment target seq num on resend request

in_session.go, pending_timeout.go, pending_timeout_test.go, resend_state.go, resend_state_test.go
=> corrects behavior where resend state is forgotten

pending_timeout_test.go, registry.go, resend_state_test.go, session.go, session_test.go
=> allow sends outside of session being logged on

in_session.go, in_session_test.go, logout_state.go, logout_state_test.go, session_test.go
previously, logout request from sender did not result in an incremented target seq num
=> correctly increments in target seq num on logout for in session state

in_session.go, in_session_test.go, logon_state.go, logon_state_test.go, logout_state.go, logout_state_test.go, pending_timeout.go, pending_timeout_test.go, session.go, session_state.go, test_helpers.go
Guarantees OnLogout is called whenever the session is disconnected and the session is logged on, or is expecting a logon response.  Previously OnLogout was called whenever the session stopped, no matter what the state.
=> onlogout calls depend on session state

acceptor.go, connection.go, in_session.go, in_session_test.go, initiator.go, internal/event.go, latent_state.go, latent_state_test.go, logon_state.go, logon_state_test.go, logout_state.go, logout_state_test.go, not_session_time.go, pending_timeout.go, pending_timeout_test.go, resend_state.go, resend_state_test.go, session.go, session_state.go, session_test.go
=> Session time

in_session_test.go, logon_state_test.go, logout_state_test.go, session.go, session_state.go, session_test.go
fixes race condition where a message can be received or sent just outside of session time.
=> checks session time before events outside of ticker

Makefile, cmd/generate-fix/generate-fix.go, fix_decimal.go, fix_decimal_test.go, fix_float_test.go, vendor/github.com/shopspring/decimal/LICENSE, vendor/github.com/shopspring/decimal/README.md, vendor/github.com/shopspring/decimal/decimal.go, vendor/vendor.json
refs #114 
* vendors shopspring decimal
* adds FIXDecimal type
* tweaks to Makefile
* DRY refactoring in generate-fix
=> FIX decimal

errors.go, logon_state.go, logon_state_test.go, session.go, session_test.go
=> reject logon support

config/configuration.go, config/doc.go, sqlstore.go, sqlstore_test.go
ripping the band aid on this.  naming necessary when SQL Logging configurations are added.
=> renames SQLStore config settings

in_session_test.go, quickfix_test.go, resend_state.go, resend_state_test.go
Observed behavior is that a peer fufills resend request, but requester appears to ignore caught up messages and issue another subsequent resend request
=> fixes bug in resend state where resend response is processed incomplete

logon_state.go, logon_state_test.go, session.go
Previously, even though a logon was received with sequence number too high, the state machine would not enter a resend state. However, the resend request would be sent so the peer would be expected to facilitate resend and the resend requester _should_ be unaffected.  In any case, this fixes that logical misstep.
=> fixes logic around logon message with sequence number too high

in_session.go, in_session_test.go, quickfix_test.go, resend_state_test.go, session.go
=> calls toApp toAdmin on resend and seq reset

field_map.go, field_map_test.go
FieldMap already has `GetInt` And `GetString`.
Then why not to have the series for sets. ;)
=> Add FieldMap.{SetInt, SetString}

logon_state_test.go, quickfix_test.go, session.go, session_test.go
=> fixes issue where initiator ignores toAdmin reset seqnum

in_session.go, in_session_test.go, logon_state.go, logon_state_test.go, quickfix_test.go, resend_state.go, resend_state_test.go, session.go
Fixes bug where a session in resend state after logon with sequence number too high will transition to inSession before receiving all messages in resend request.  Could result in needless resend request if peer doesn't follow normal resend behavior.
=> Resend logon fix

config/configuration.go, tls.go, tls_test.go
Currently I am working on conformance tests of a FIX service. 
It offers TLS session without CERT info.
So I need to tweak the library to do.
---
FIX servicer may offer to use TLS connection without any CERT info,
basically for conformance testing.
With this switch, the session will use Go's tls.Config
```go
tls.Config{InsecureSkipVerify: true}
```
To prevent accidental behaviour in production service, the switch
only activate if `SocketPrivateKeyFile` and `SocketCertificateFile`
is omitted.
=> Add config.SocketTLSForTesting(bool)

in_session.go, logon_state.go, message.go, message_router.go, message_test.go, session.go
Utility methods.
To me, they are useful. How are they to you?
Speaking of the method name  `HasMsgTypeOf`, `IsMsgTypeOf` would be more appropriate? Or more better name we can have?
Thank you.
=> Add Header.{GetMsgType, HasMsgTypeOf}

file_log.go, file_log_test.go, in_session.go, in_session_test.go, log.go, message.go, message_test.go, null_log.go, quickfix_test.go, screen_log.go, session.go, session_state.go, session_test.go, validation_test.go
* Removes unnecessary string allocation at the top of the Log interface
* remove Build from public Message interface
* consistent receiver on Message methods
=> API polish

acceptor.go, field_map.go, in_session.go, in_session_test.go, latent_state.go, logon_state.go, logon_state_test.go, logout_state.go, logout_state_test.go, message.go, message_pool.go, message_router_test.go, message_test.go, not_session_time.go, quickfix_test.go, repeating_group_test.go, resend_state.go, session.go, session_state.go, session_test.go, validation_test.go
Drastically reduces the number of allocations for inbound messages
=> Using a pool for inbound messages

message.go
This is necessary to get on the wire string format for group messages.
Fixes issue introduced in #260
=> message.String() returns rawMessage if set, builds otherwise

in_session.go, message.go, message_test.go, session.go, session_factory.go, session_state.go
Incremental change to support #276. Allows data dictionary to help parse custom header and trailer fields in the Header and Trailer FieldMaps respectively.
=> use data dictionary for parsing fix messages

_sql/postgresql/event_log_table.sql, _sql/postgresql/messages_log_table.sql, _sql/postgresql/sessions_table.sql
Without time zone:
- When creation_time is saved to db, it is save as local time e.g `+0200 EET`
- When creation_time is read from db, it is read as `+0000 +0000`
E.g:
1. creation_time is initialized: `2014-03-26 17:05:30.889109334 +0200 EET`
2. Save into db it becomes: `2014-03-26 17:05:30.889109`
3. Read from db to creation_time, it becomes: `2014-03-26 17:05:30.889109 +0000 +0000`
=> (1) != (3)
With time zone: (1) == (3)
Reference: https://github.com/lib/pq/pull/247#issuecomment-38695036
=> Use timestamp with time zone for postgres sql

cmd/generate-fix/internal/templates.go
Header and Trailer templates were not using ImportRootPath for importing generated enums, fields and tag packages.  This change will allow generated header and trailer types to use custom fields not in the quickfix packaged generated types.
=> header and trailer templates use rootpath

datadictionary/build.go, datadictionary/build_test.go, datadictionary/xml.go, datadictionary/xml_test.go
Adds some defensive coding to verify valid datadictionary input.   The `<fix>` attributes`type`, `major`, and `minor` are required.
=> adds validation to datadictionary builder

vendor/vendor.json
used for tests, addresses `OSAtomicCompareAndSwapPtrBarrier` warning seen on macs
=> updates sqlite3 driver

settings.go, settings_test.go
`BeginString` must be FIX.4.0 to FIX.4.4 or FIXT.1.1
=> validate beginstring configuration

message.go, message_test.go, parser.go, parser_test.go, tag_value.go, tag_value_test.go
instead of panic, correctly handle parsing malformed messages in cases where a message is blank, or tag values have no tags.
=> message parse edge cases

store.go
@cbusbey I already got it back again... See the output below:
```
==================
WARNING: DATA RACE
Read at 0x00c42019ea28 by main goroutine:
github.com/svanharmelen/xtdr/vendor/github.com/quickfixgo/quickfix.(*memoryStore).NextSenderMsgSeqNum()
<autogenerated>:1 +0x53
github.com/svanharmelen/xtdr/vendor/github.com/quickfixgo/quickfix.(*session).prepMessageForSend()
/Users/svanharmelen/Documents/GoCode/src/github.com/svanharmelen/xtdr/vendor/github.com/quickfixgo/quickfix/session.go:279 +0x9a
github.com/svanharmelen/xtdr/vendor/github.com/quickfixgo/quickfix.(*session).queueForSend()
/Users/svanharmelen/Documents/GoCode/src/github.com/svanharmelen/xtdr/vendor/github.com/quickfixgo/quickfix/session.go:204 +0xcd
github.com/svanharmelen/xtdr/vendor/github.com/quickfixgo/quickfix.SendToTar …
```
=> Fix a data race condition in the memoryStore

registry.go
useful for test cleanup in other packages.  an example, when SessionIDs are tracked in `sessions`:
```go
for _, s := range sessions {
err := fix.UnregisterSession(s)
if err != nil {
log.Printf("could not remove session %s: %s", s.String(), err.Error())
}
}
```
=> added new exported unregister session call

internal/event_timer.go
Sending multiple messages in rapid succession (or concurrently) causes deadlock.
While building an Acceptor implementation, I experienced the symptoms of a deadlock when the server happened to receive two requests in quick succession. The messages would be processed on the same goroutine as the FromApp callback and a response sent back using SendToTarget. The session thread got stuck in the second call to SendToTarget.
To debug the issue, I created an Initiator (which runs in a separate process on the same machine) that generates many requests:
```
for {
time.Sleep(time.Second * 10)
for i := 0; i < 10; i++ {
go func() {
log.Println("before send")
must(quickfix.SendToTarget(NewRequestMessage(), sessionId))
log.Println("after send")
}()
}
}
```
Surprisingly the Initiator would also deadlock …
=> Change EventTimer to reset its Timer without requiring a reset channel

config/configuration.go, config/doc.go, session_factory.go, validation.go, validation_test.go
This is a PR for #336.
Let me know if I missed anything.
=> Adds support for RejectInvalidMessage configuration.

message.go, message_test.go
This is a followup to https://github.com/quickfixgo/quickfix/issues/338 
I added a  `CopyInto` method to message implementing the deep copy of the message is being called to.
=> Message deep copy

message.go
Sorry, while re-looking at what I did with https://github.com/quickfixgo/quickfix/pull/341 I spotted a debug print I left.
This removes it.
=> Removed debug print

config/configuration.go, initiator.go
=> Support timeout on ssl connection #347

field_map.go, field_map_test.go, message.go, message_test.go
It's unclear if we should copy `Message.rawMessage` here. I chose not to in case the original buffer is changed. I think the point of `Message.CopyInto()` is to decouple the new instance from the old, and shouldn't be used in high-performance scenarios anyway.
I removed the error return value because I don't understand when you'd expect an error. We could add it back for API compatibility. I don't think the name `CopyInto()` is idiomatic Go, but I don't see any obvious examples for naming something similar.
=> Fix `Message.CopyInto()` to fully deep copy and remove the error return value #338

logon_state.go, mongostore.go, session.go, session_state.go, session_test.go
Includes minor lint fixes for mongo store
=> Initiator ResetSeqNumFlag fix

config/configuration.go, config/doc.go, tls.go, tls_test.go
I realise this has been covered in #311 but I'm providing a pull request, and there is a potential security issue/footgun with the current behaviour.
In my experience, at least two major exchanges (ICE and CME) do not use client certificate authentication for their FIX trade capture endpoints, and therefore quickfixgo cannot be used with them currently. Instead, the server provides a TLS certificate and login is via username/password field in the login message.
There is a very insecure workaround right now - setting SocketInsecureSkipVerify=Y has the side effect of allowing a TLS connection even without client certificates. However, it also does not verify the received certificates which obviously a presents a large security risk (especially given that both ICE and CME provide valid, …
=> Add SocketUseSSL parameter to allow SSL/TLS without client certs

config/configuration.go, config/doc.go, internal/session_settings.go, session.go, session_factory.go, session_factory_test.go, session_state.go
Resolves
*  https://github.com/quickfixgo/quickfix/issues/296 and exposes a logout timeout parameter as a config parameter. Defaults to 2 seconds.
* https://github.com/quickfixgo/quickfix/issues/295 and exposes a logon timeout parameter as a config parameter. Defaults to 10 seconds.
Note
* There might be some room for improvement with unit tests / acceptance tests in this area..
=> Adds LogoutTimeout and LogonTimeout as config parameters

config/configuration.go, config/doc.go, initiator.go, tls.go, tls_test.go
Fixes #384:
* Support TLS SNI by passing in ServerName configuration
* If 
-- InsecureSkipVerify is false 
-- ServerName not configured
then copy the host part of the connection address as the ServerName. This essentially restores the behavior before https://github.com/quickfixgo/quickfix/commit/ce2275bf2c97f679d58b639e7b90d8b3e3e34b8b
Tests done:
* Unit tests - passing
* Manual test with the test code in #384 - passing
=> Tls server name config

acceptor.go, config/configuration.go
I'm using the `DynamicSessions` setting, but I'd like to allow users to connect multiple times using the same SenderCompID. 
Right now, that's  not possible because the Acceptor generates the SessionID without a Qualifier. I've added a new setting, such that when `DynamicQualifier=Y`, it will automatically add a distinct qualifier to dynamic session IDs.
=> Add DynamicQualifier setting to enable duplicate dynamic sessions 

logon_state.go, logon_state_test.go
Fixes #369
Include expected sequence number in text field of Logout response to Logon request with sequence number too low.
=> Include reason in text field of Logout if seq num too low in Logon.

acceptor.go
As described in https://github.com/quickfixgo/quickfix/issues/388 I'd like to implement IP whitelisting functionality.
I've noticed that QuickFIX/J implements this functionality through the `AllowedRemoteAddresses` config (_"List of remote IP addresses which are allowed to connect to this acceptor"_):
https://www.quickfixj.org/usermanual/2.1.0/usage/configuration.html 
While this is a good solution for static sessions, it doesn't work for my use-case because I'm using dynamic sessions. 
The simplest solution I could think of was to add a `RemoteAddr(sessionID)` method on the Acceptor that can be used to get the address for a particular session.
=> Expose IP address for Acceptor 

acceptor.go
Adding ConnectionValidator interface allows implementation of any customer's validation/authentication. Possible use cases may include mutual TLS authentication or IP white-listening tied up with certain SenderCompID. The validator is optional and the behaviour of existing clients will not change.
This will also address #388 
The `Acceptor` is unfortunately not covered with tests and covering `handleConnection` to verify the validator is working as expected will require a significant refactoring, or a more end-to-end style test.
Any feedback is welcome, if there are other ways to handle the strict mTLS auth that I've not found yet - please let me know.
=> An option for a custom authentication logic

tls.go
I've encountered a FIX server that I cannot connect to due to the fact that TLS 1.2 is being the default.
=> Specify TLS minimum version explicitly

sqlstore.go, sqlstore_test.go
Addresses https://github.com/quickfixgo/quickfix/issues/284 without an overhaul 
- Adds a function to replace `?` placeholders with `$1` `$2` etc as required by postgres
- Runs all sql statements through the replacement func at query time (nop for sql)
- In theory any other placeholder format could be added pretty easily on top
=> Lightweight support for Postgresql

datadictionary/datadictionary.go
instead of having to provide a path it would be nice if we could provide the src ourselves, as this allows embedding the src into the binary, for example with `go:embed` added in go 1.16 :)
this seems to be the simplest way of making this possible without having to expose the `builder` and allows anyone to provide the source of the datadict in any way they like as a simple `bytes.NewBuffer([]byte{})` or with anything else that provides a `io.Reader`!
=> add ParseSrc function so the source of the datadict doesn't have to be a filepath.

acceptor.go
=> Fix concurrent map write

tls.go, tls_test.go
I think the `SocketUseSSL` config actually makes the code skips the `SocketCAFile` config when it is set to `Y`. 
Since we have `SocketCAFile` option to use a supplied CA certificate to verify server identity, we still need the part of the code to add the supplied CA certificate to the `CertPool` and other functionalities. Skipping client authentication shouldn't skip everything.
=> Make use of SocketCAFile config

application.go, datadictionary/datadictionary.go, field.go, filestore.go, go.mod, go.sum, internal/time_range.go, log.go, repeating_group.go, session_factory.go, session_settings.go, session_state.go, store_test.go
- Adding more context information to some errors
- Updating some docs to match the golang standards
=> Improve error information

.github/workflows/ci.yaml
GitHub asks users to define workflow permissions, see https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ and https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token for securing GitHub workflows against supply-chain attacks.
The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) also treats not setting token permissions as a high-risk issue. 
This repository has a Scorecards score of 5.4/10 with 10 being the most secure. The `Token-Permissions` category has a score of 0/10.
This file was fixed automatically using the open-source tool https://github.com/step-security/secure-workflows. If you like the changes and merge them, please …
=> Add token perms for ci.yaml

repeating_group.go
Use of `MaxInt64` prevents compilation on 32-bit systems
=> use MaxInt32 values to enable compilation on 32-bit systems

session.go
=> Dynamic session deadlock bug fix

session.go
We have floating deadlocks when stop the Acceptor. Firstly deadlocks appear in acceptor.go:354. This connected with fact that session.stop() func is called not once. It can be called from 3 places in acceptor (but static, not dynamic session, could be stopped only once) : acceptor.go:354 and acceptor.go:323 and acceptor.go:129!  
That is why after first call session.stop() we write `s.admin <- stopReq{}` then this s.admin chan processed here in select statement session.go:772 while `for !s.Stopped()`. and after processing here in session.go:732 we switch s.Stopped to false and quit from select loop and have never listen s.admin more! Second call session.stop() and writing to s.admin calls deadlock(( 
My proposal is add sync.Once() inside call of session.stop() and write s.admin <- …
=> Multi dynamic session stop deadlock

session.go
Co-authored-by: Alexis Masson <alexis.masson@artex.io>
Signed-off-by: Sylvain Rabot <sylvain@abstraction.fr>
=> Align session's ticker with round second

repeating_group.go, repeating_group_test.go
The ```RepeatingGroup``` tags are not created during the read process. Tag values are there but tags are not copied over / read. If `CopyInto` is used to copy from old `FieldMap` to new, existing tags from old one will be lost during the [fields setting process](https://github.com/quickfixgo/quickfix/blob/main/repeating_group.go#L116)
Can try to reproduce like this: 
```go
symGroup := quoterequest.NewNoRelatedSymRepeatingGroup()
sym := symGroup.Add()
sym.SetSymbol("symbol")
sym.SetOrderQty(decimal.NewFromFloat(1), 4)
sym.SetQuoteRequestType(enum.QuoteRequestType_AUTOMATIC)
fixmsg := quoterequest.New(field.NewQuoteReqID("testId"))
fixmsg.SetNoRelatedSym(symGroup)
msg := quoterequest.FromMessage(fixmsg.ToMessage())
if syms, err := msg.GetNoRelatedSym(); err == nil {
newSyms := …
```
=> Fix repeating group read tags lost

filestore.go, mongostore.go, sqlstore.go
* Dynamic sessions are not added to the settings until after the session
factory has created the sessions. In this scenario the filestore and
sqlstore are unable to get the settings and fail to create the various
message stores. Often these settings are set globally so we should try
falling back before failing to create the message store.
Fixes #484
=> Allow stores to fall back to global settings for dynamic sessions

message.go, message_test.go
Add `message.Bytes()` method as an alternative to `message.String()` to avoid the string conversion in case you need to use the raw bytes.
=> Add message.Bytes() to avoid string conversion

field_map.go, field_map_test.go
Remove the specific tag from the FIX message. This is helpful when dealing with clients not following FIX specifications strictly
=> Remove tag from field map

session.go
if session disconnected during sendBytes, session.messageOut
may be set to nil before write in session.onDisconnect()
=> Avoid to block thread while write to a nil channel

_test/definitions/server/fix50sp1/14i_RepeatingGroupCountNotEqual.def, _test/definitions/server/fix50sp2/14i_RepeatingGroupCountNotEqual.def, validation.go, validation_test.go
Now, `RejectInvalidMessage` setting is not used when validating a FIX.5.0+ message using FIXT.1.1. It is not possible to receive a message containing a tag not specified.
=> Check RejectInvalidMessage on FIXT validation

internal/event_timer.go, internal/event_timer_test.go
Resolves https://github.com/quickfixgo/quickfix/issues/581
=> Makes event timer stop idempotent

config/configuration.go, config/doc.go, internal/time_range.go, internal/time_range_test.go, session_factory.go, session_factory_test.go, session_test.go
Hi there, I should have opened an issue to discuss, but we had another requirement for a FIX integration we have just started running in production with a large exchange, and this is our first pass at solving this, so I thought I'd submit upstream for feedback in case we've missed something.
The session we currently have with the exchange requires *daily* sessions but only during the week (Monday - Friday). We discovered when trying to define the session that including `StartDay/EndDay` properties in the session config made the session into a week long version so we wouldn't get the daily session end happening as required. To give this example again more concretely - with the following settings:
- StartTime: 08:00:00
- EndTime: 16:30:00
- StartDay: Monday
- EndDay: Friday
our session …
=> Add Weekdays config setting as included in QuickFIX/J

filestore.go, mongostore.go, sqlstore.go
If update sequence number cache before store it to mongodb, sql or file, and then get an error, will cause the sequence number to be discontinuous. So, store sequence number before update cache.
=> Fix sequence number bug when storage fails

in_session.go, message.go, message_test.go
refs #608 #568 
This is a workaround for the fact that we currently rely on the generated Message types to properly serialize/deserialize RepeatingGroups.
In other words, **we cannot go from bytes to a Message then back to bytes**, which is exactly what we need to do in the case of a Resend.
This adds the `Message.buildWithBodyBytes([]byte)` func that lets us pull the Message from the Store, parse it, update the Header, and then build it back into bytes using the original Body.
Stay tuned for a more complete solution that fully solves the problem beyond just Resend.
Note: The only standard non-Body group is NoHops.  If that is used in the Header, this workaround may fail.
=> Preserve original body when resending

validation.go, validation_test.go
The edge case is described in the unit test added in this PR
When a group field contains more than one element and one of the elements has less params (because they are optional), it will be parsed incorrectly due to the change added in #368
e.g.
```
453=2448=PARTYID452=3523=SUBID448=PARTYID2452=3
```
in the example, the last element does not have _523_ defined
this means that a fix for #365 / #366 is still required
=> Group field whose elements do not have the same fields are incorrectly parsed

logon_state_test.go, session.go, session_state.go
1. Very high lock contention on `session.sendMutex`
2. Random huge delays, after sending a message out getting the response taking to match time ~5s in some cases
3. Main [session loop](https://github.com/quickfixgo/quickfix/blob/3bf2b871219bd9921c206adf59585b920c133538/session.go#L801-L821)  is either sending a batch (and blocking until all messages in the batch are sent) or reading just ONE incoming message. 
So, if there are many messages in the slice `toSend`, session from our side is blocked until all the messages are sent. 
At the same time, if halfway (when half of the messages in `toSend` have been sent) the other side cannot accept more messages (maybe cause of a buffer overflow) in order to be unblocked, we need to consume some of the incoming messages, which with the current …
=> Escape send queued when blocked on connection side

logon_state_test.go, session.go, session_state.go
When log on request was queued because cannot be send due to connection not ready,
Then it goes through the [main session
loop](https://github.com/alpacahq/quickfix/blob/5dcde41f3e6e68e93e1fd381761cd9c7843aec43/session.go#L821-L841) which leads to
[SendAppMessages](https://github.com/alpacahq/quickfix/blob/5dcde41f3e6e68e93e1fd381761cd9c7843aec43/session_state.go#L107-L111)
But, since session is not logged on yet because the message queued is the log on message, we drop the `toSend` queued messages so we lose the log on message itself.
For important messages like Logon/Logout/Resend/SequenceReset we block until sent.
=> Bug: For Logon/Logout/Resend/SequenceReset messages we should wait until sent

Makefile, session.go, session_state.go, session_test.go
=> Corrects ResetOnLogon for initiators

Makefile, in_session.go, message.go, message_test.go, session.go
Resolves https://github.com/quickfixgo/quickfix/issues/608 and https://github.com/quickfixgo/quickfix/issues/550
=> Maintain repeating group field order when parsing messages

in_session.go, in_session_test.go
If an out-of-sequence Logout or Test Request is received, either during `inSession` or `resendState`, it should not result in incrementing the next expected target sequence number, or else we have a chance of missing a message.
Consider the scenario below from the point of view of an Initiator.
We receive a Logout request from Acceptor:
```
FIX incoming [FIX.4.2:SENDER->TARGET |8=FIX.4.2|35=5|34=100|
FIX event [FIX.4.2:SENDER->TARGET - Received logout request]
FIX event [FIX.4.2:SENDER->TARGET - Sending logout response]
FIX outgoing [FIX.4.2:SENDER->TARGET - |8=FIX.4.2|35=5|34=10|
FIX event [FIX.4.2:SENDER->TARGET - Disconnected]
```
After some time we try to Logon again:
```
FIX event [FIX.4.2:SENDER->TARGET - Sending logon request]
FIX outgoing [FIX.4.2:SENDER->TARGET - …
```
=> Do not increment NextTargetMsgSeqNum for out of sequence Logout and Test Requests

dialer.go, initiator.go
This commit fixes an issue when calling Start() and then Stop() on the initiator while the connection is likely to fail and timeout. Sending a SIGTERM and calling Stop() will block since Dial will attempt to connect until it times out and returns on the `waitForReconnectInterval` call.
We mitigate this problem by using a `proxy.ContextDialer` and allowing to pass a context with cancellation method to the `dialer.DialContext` method on `handleConnection`.
We need to start a routine listening for the `stopChan` in order to call cancel() explicitly and thus exit the DialContext method.
Note: there are scenarios where `cancel()` will be called twice, this choice was made in order to avoid a larger refactor of the reconnect logic, but since the call to `cancel()` is idempotent, this doesn't …
=> Fix stuck call to Dial when calling Stop on the Initiator

message.go
Not a huge improvement but an improvement nonetheless.
```
goos: darwin
goarch: arm64
pkg: github.com/quickfixgo/quickfix
│    old3     │                new3                │
│   sec/op    │   sec/op     vs base               │
ParseMessage-8   680.6n ± 0%   650.0n ± 0%  -4.49% (p=0.000 n=20)
```
=> Use bytes.Count to count the number of message fields

tag_value.go
```
goos: darwin
goarch: arm64
pkg: github.com/quickfixgo/quickfix
│     old     │          new-no-indexbyte          │
│   sec/op    │   sec/op     vs base               │
ParseMessage-8   695.2n ± 1%   628.2n ± 1%  -9.64% (p=0.000 n=20)
```
=> Optimize tag value parsing

field_map.go, message.go
```
goos: darwin
goarch: arm64
pkg: github.com/quickfixgo/quickfix
│     old     │          new-parse-no-lock          │
│   sec/op    │   sec/op     vs base                │
ParseMessage-8   695.2n ± 1%   591.0n ± 0%  -14.99% (p=0.000 n=20)
```
=> Only lock fieldmap once during message parsing

config/configuration.go, session_factory.go, session_settings.go, session_settings_test.go, tls.go, tls_test.go
This change is intended to allow users to configure TLS settings in the form of raw byte slices. This is particularly useful for situations where the FIX application is running in a cloud environment (e.g. k8s) and session configuration is loaded from a database (rather than a static file). In this scenario it is much more convenient to be able to load TLS key pairs from the DB in the form of byte slices, than it is to have to ensure files with the correct names exist on some persistent volume such that the FIX app can load them from disk correctly.
To support this we changed the basic type stored within SessionSettings to be a byte slice which means we are able to still support the existing settings model, but also handle raw byte slices we can use for TLS setup. The existing API exposed …
=> Support TLS configuration as raw bytes

accepter_test.go, acceptor.go
TLS certs go stale / expire overtime.
When they do, they need to be renewed.
Originally, when a server (acceptor) starts up, it configures its tls.Config to use for tls connections. 
When this tls.Config uses / is set up with `Certificates []Certificate`, then the cert will be stored / remain in memory, and will be static in nature. Any renewal on the disk would not affect that Certificates slice. The only way to effectuate the new certs is to reboot the server.
This reboot may be undesirable / unnecessary, if the server would be able to load the server cert on demand.
Golang solves this issue, by allowing the tls.Config to load the server cert by a user specified function (`GetCertificate`).
This PR would allow the developer to specify a tls.Config of their choice, and in turn would …
=> allow the clients of acceptor to specify their own tls.Config

in_session.go, logon_state_test.go, session.go
https://github.com/quickfixgo/quickfix/issues/410
=> Check logon auth before resetting store

internal/testsuite/store_suite.go, store/file/file_store.go
In `store/file/file_store.go` there is currently a `sync.Map` that maintains the offset of every single message in the file store. 
Sessions that get up into the tens or hundreds of millions of messages grow this map immensely! There's no need to keep this around in memory - when iterating through messages, you're going to disk anyway, and it is a very cheap I/O operation to scan through the header file as well to avoid bloating memory
=> File store uses files exclusively

cmd/generate-fix/internal/templates.go
This updates Go code template to avoid unkeyed fields usage for exported struct.
I'm using `generate-fix` command to generate my own custom FIX application. 
However, Go standard linter, `go vet`, raises an alert because the generated Header/Trailer struct literal uses unkeyed fields.
https://github.com/golang/tools/blob/master/go/analysis/passes/composite/composite.go
While I understand the unkeyed field usage is valid for generated code, it can be somewhat inconvenient to exclude generated code from vet target or disable composite analysis entirely by `go vet -composites=false ./...`.
It would be preferable if the generated code adhered to the recommended style to avoid such issues.
=> Avoid unkeyed fields usage for exported struct in generated code

config/configuration.go, store/sql/sql_store.go, store/sql/sql_store_test.go
=> Make DB Store table names configurable

internal/time_range.go, internal/time_range_test.go
The current IsInRange() method produces incorrect results when the time range crosses midnight (StartTime > EndTime) and "Weekdays" is configured. For example, when Weekdays=[Sunday, Monday, Tuesday, Wednesday, Thursday], the system will incorrectly identify Friday's time period as not belonging to the time period.
**Reproduce**
Config:
```
Weekdays:  []string{"Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"},
StartTime: "19:00:00",
EndTime:   "06:00:00",
Timezone:  "America/New_York",
```
IsInRange() result before change:
```
[Sunday]2025-06-08 00:00:00 = true
[Sunday]2025-06-08 01:00:00 = true
[Sunday]2025-06-08 02:00:00 = true
[Sunday]2025-06-08 03:00:00 = true
[Sunday]2025-06-08 04:00:00 = true
[Sunday]2025-06-08 05:00:00 = true
[Sunday]2025-06-08 06:00:00 = true …
```
=> Fix the issue of incorrect time range calculation across days

README.md
Actual link (404): http://quickfixgo.org/docs 
New link: https://quickfixengine.org/go/documentation/
=> update go api documentation link
